[FEATURE/UPGRADE] react modal package with portal / eslint / jest
dotmind/react-modals pull request #1
Opened 2022-02-09 15:40 UTC by Scredi

2022-02-23 10:17 UTC, vcarrere33 commented on README.md
> +You need react >= 16.0.
ça serait pas plutot react 17 ?

2022-02-23 10:17 UTC, vcarrere33 commented on public/index.html
> +    <title>Demo</title>
il sert a quoi ce fichier ?

2022-02-23 10:17 UTC, vcarrere33 commented on src/__tests__/index.test.tsx
> +    const { baseElement, queryByText } = render(<Modal modalOpen={true} onClose={() => { return; }}>modal content</Modal>);
la props onClose est obligatoire ?

2022-02-23 10:17 UTC, vcarrere33 commented on src/@types/index.d.ts
> +declare module '*.scss';
Pourquoi devoir déclarer le scss ?

2022-02-23 10:17 UTC, vcarrere33 commented on serve.js
> +liveServer.start({
Je veux bien quelques explications pour comprendre le fonctionnement de ça :)

2022-02-23 10:17 UTC, vcarrere33 commented on src/dev.tsx
> +const App: React.FC = () => {
Pourquoi ce fichier s'appelle dev ?

2022-02-23 10:17 UTC, vcarrere33 commented on src/index.tsx
> +          containerClassName || '',
pourquoi pour les classnames ne pas faire 
```className={`react-modal-container ${containerClassName || ''}`}``` ?

2022-02-23 10:17 UTC, vcarrere33 commented on src/index.tsx
> +    return createPortal(
je suis pas sur mais je me demande si c'est pas mieux de faire

return createPortal(renderModal, document.body)

et renderModal renvoi null si il y a rien

2022-02-23 10:17 UTC, vcarrere33 commented on src/styles.scss
> +    z-index: 99999;
si tu as react-modal-container avec un z-index tu as aussi besoin de mettre un z-index sur le content ?

2022-02-23 10:29 UTC, anthlasserre requested changes

2022-02-23 10:29 UTC, anthlasserre commented on README.md
> +  }, []);
Tu peux créer une seule fonction je pense.
```suggestion
  const handleChangeModal = useCallback(() => {
    setModalOpen((prevState) => !prevState);
  }, [setModalOpen]);
```

2022-02-23 10:29 UTC, anthlasserre commented on src/__tests__/index.test.tsx
> +    const { baseElement, queryByText } = render(<Modal modalOpen={true} onClose={() => { return; }}>modal content</Modal>);
```suggestion
    const { baseElement, queryByText } = render(<Modal modalOpen={true} onClose={() => null}>modal content</Modal>);
```

2022-02-23 10:29 UTC, anthlasserre commented on src/__tests__/index.test.tsx
> +    const { baseElement, queryByText } = render(<Modal modalOpen={false} onClose={() => { return; }}>modal content</Modal>);
```suggestion
    const { baseElement, queryByText } = render(<Modal modalOpen={false} onClose={() => null}>modal content</Modal>);
```

2022-02-23 10:29 UTC, anthlasserre commented on src/dev.tsx
> +  }, []);
Tu peux simplifier comme ça je pense.
```suggestion
  const handleChangeModal = useCallback(() => {
    setModalOpen((prevState) => !prevState);
  }, [setModalOpen]);
```

2022-03-03 14:08 UTC, Scredi commented on README.md
> +  }, []);
Merci pour la review :)

2022-03-03 14:10 UTC, Scredi commented on src/__tests__/index.test.tsx
> +    const { baseElement, queryByText } = render(<Modal modalOpen={true} onClose={() => { return; }}>modal content</Modal>);
done

2022-03-03 14:11 UTC, Scredi commented on src/__tests__/index.test.tsx
> +    const { baseElement, queryByText } = render(<Modal modalOpen={false} onClose={() => { return; }}>modal content</Modal>);
done

2022-03-03 16:51 UTC, vcarrere33 approved these changes

2022-03-03 16:51 UTC, vcarrere33 approved these changes

2022-03-31 10:44 UTC, merged